---
abstract: 'Asynchronous socket policy file server for a flash socket connection.'
author:
  - 'keroyonn <keroyon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-FlashSocketPolicy
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0
  AnyEvent: 0
  AnyEvent::Handle: 0
  AnyEvent::Socket: 0
  Getopt::Long: 0
  Pod::Usage: 0
  Text::MicroTemplate: 0
  Try::Tiny: 0
  perl: 5.8.8
resources:
  homepage: http://github.com/keroyonn/p5-AnyEvent-FlashSocketPolicy/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/keroyonn/p5-AnyEvent-FlashSocketPolicy.git
version: 0.01_1
